### ISSUE TITLE
Allow arrivals without a STAR

### ISSUE THREAD

**Issue by jlefkoff** [mmp/vice#219]
Smaller TRACONs sometimes do not have any STARs. In the case of GTF, all arrivals route direct to the VOR over the airport, and are vectored for an approach. This works fine by putting "GTF" as the `STAR` in the `arrival_groups` section, but results in non-realistic phraseology as seen in the screenshot.
<img width="433" alt="Screenshot 2024-05-18 at 8 57 28 PM" src="https://github.com/mmp/vice/assets/29154743/f1a58426-a9cd-44d6-9e08-7e5d00d689e0">

**Comment by radarContacto** [comment]
I agree. Also, even large TRACONs have non-STAR routing for some aircraft (slower piston type etc). https://discord.com/channels/1090685318014976081/1240147831751442453

**Comment by jlefkoff** [comment]
I think this (and facilities that require it) should wait until we have better support for GA with N numbers and airlines not in the openscope file (example is [Air Spur](https://en.m.wikipedia.org/wiki/Corporate_Air) which regularly flies to GTF).

**Comment by mmp** [comment]
This should be fixed for the next release. Now "star" doesn't need to be given for arrivals; if there is none, the pilot contact message will just be ".. inbound FIX", where FIX is the next fix in their route rather than saying they're on a STAR. (I'm open to other pilot phraseology if you have suggestions.)
